# This is a basic workflow to help you get started with Actions

name: AzureCR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04 # ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - uses: azure/docker-login@v1
         with:
            login-server: wechuli.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

       - run: |
          docker pull wechuli.azurecr.io/hello-world:v1
       - name: push image
         run: |
           docker pull mcr.microsoft.com/hello-world
           docker tag mcr.microsoft.com/hello-world wechuli.azurecr.io/hello-worldss:v1
           docker image list
           docker push wechuli.azurecr.io/hello-worldss:v1
           
           
        
